### ISSUE TITLE
Support async/await in jest tests

### ISSUE THREAD

**Issue by thektan** [liferay/liferay-npm-tools#105]
When using async/await in tests the following error is thrown: 
```
ReferenceError: regeneratorRuntime is not defined
```

### Option 1
According to [Jest docs](https://jestjs.io/docs/en/tutorial-async#async-await):
> To enable async/await in your project, install @babel/preset-env and enable the feature in your babel.config.js file.

In `.babelrc`
```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current"
        }
      }
    ]
  ]
}
```
(Sources: https://github.com/facebook/jest/issues/3126#issuecomment-483320742, https://github.com/babel/babel/issues/7601#issuecomment-374566429)

### Option 2
Installing `@babel/plugin-transform-runtime` and adding the following configuration to `.babelrc`
```json
{
  "env": {
    "test": {
      "plugins": ["@babel/plugin-transform-runtime"]
    }
  }
}
```
(Sources: https://github.com/facebook/jest/issues/3126#issuecomment-465926747, https://github.com/babel/babel/issues/8829#issuecomment-456524916)

### Option 3
Importing `babel-polyfill` to the jest `setup.js` file. Which would mean adding `babel-polyfill` as a new devDependency.
```javascript
import 'babel-polyfill';
```
(Source: https://github.com/babel/babel/issues/5085#issuecomment-277544677)

## Final Comments
I'm currently using Option 2 since it scopes the plugin to just the tests (where the issue is only occurring), but I'd like to hear everyone else's opinion since I haven't noticed any differences with any of these fixes besides Option 3 throwing a new error `Warning: Can't perform a React state update on an unmounted component` in the tests (but that's probably something I'd need to fix in the component/tests itself).

**Comment by wincent** [comment]
Given that we currently use Node v10.15.1 in liferay-portal (which has native `async`/`await` support), it would be nice to see how far we can get with "Option 1", because it means Babel will skip some of the heavier-weight transforms that it does (including relying on the regenerator runtime).

**Comment by thektan** [comment]
@wincent It looks like we could do something like this example from the [jest docs](https://jestjs.io/docs/en/getting-started):

> Jest will set process.env.NODE_ENV to 'test' if it's not set to something else. You can use that in your configuration to conditionally setup only the compilation needed for Jest, e.g.

```javascript
// babel.config.js
module.exports = api => {
  const isTest = api.env('test');
  // You can use isTest to determine what presets and plugins to use.

  return {
    // ...
  };
};
```

We also might need to add `jest-babel` and `@babel/core`? The docs also say:
> To use Babel, install required dependencies via yarn:

```
yarn add --dev babel-jest @babel/core @babel/preset-env
```

**Comment by wincent** [comment]
Closing this because I am about to cut a release, so this will go to liferay-portal master today (at least, I'll submit the PR today).
