### ISSUE TITLE
Adjust command and config names for consistency

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-npm-tools#110]
Will be a breaking change, so sticking in v3.0.0 milestone.

Let's take the opportunity to make the naming as consistent as possible across liferay-portal, liferay-npm-scripts, and our other GitHub projects.

### Current status

- liferay-portal defines gradle tasks:
  - formatSource (fixes everything: formatting and lints)
  - checkSourceFormatting (checks everything: formatting and lints)
- liferay-portal "package.json" [script names](https://github.com/liferay/liferay-frontend-guidelines/blob/d84a62587e829c6515a9312d266790758636e67f/guidelines/dxp/formatting.md):
  - format
  - checkFormat
- Invoke liferay-npm-scripts subcommands:
  - format
  - lint
- And use globs from npmscripts.config.js properties:
  - format
  - lint
- And invoke the underlying commands:
  - `prettier --write` (previously `csf -i`)
  - `prettier --check` (previously `csf`)
- GitHub projects define "package.json" scripts:
  - "format"
  - "format:check"
  - "format:changed" (some of them do, anyway)
  - "lint"
  - "lint:fix"
  - "lint:quiet" (some of them do: this issues only errors, ignorning warnings; good for legacy projects where we're buried by lints)

Observations:

- In liferay-portal, "The Portal Way™" is to have one command that reports all possible issues (corresponding to "checkFormat" in the "package.json" scripts) and one that fixes all possible issues (corresponding to "format" in the "package.json" scripts).
- In our open source projects, we've divided the concerns in a different way: "format" scripts deal with how the source appears, and "lint" scripts deal with non-presentational problems in the source. Furthermore, we use ":" to create a namespace in which we can add variants such as "format:changed" or "lint:quiet".
- These two approaches don't harmonize very well right now:
  - For example Portal's idea of "formatting" (really, "fixing") corresponds to "format" and "lint:fix" in our GitHub projects.
  - Portal's idea of "checking format" (really, checking everything) corresponds to "format:check" and "lint" in our GitHub projects.
  - Why is it "format"/"lint:fix" on one hand and "format:check"/"lint" on the other? Because we've optimized for the common cases in our GitHub projects: you are more likely to run "format" blindly (because it is safe, safe enough to make it happen on every save or even more often than that), so it is the shortest command; likewise, you are more likely to run "lint" than "lint:fix" because the latter is usually something that you'd want to manually review.

### Future requirements

- liferay-npm-scripts will run more linters to cover the current gaps:
  - when checking: `eslint`, probably `csslint`, probably `csf` (just for .soy and .jsp) etc.
  - when fixing: the same tools, but with `--fix` options when such options exist.

### Intermediate requirements

- We want the ability to run tools in isolation during the migration: for example, we want to be able to run just ESLint (see #109), so that we can asses the scope of our lint violations before integrating it into the build.

### Summarizing

Assuming we had `eslint` (etc) integrated as things currently look, we'd have something like this:

| Gradle name           | Portal name | Subcommand name | Config key | Command(s)                  | GitHub name  |
| --------------------- | ----------- | --------------- | ---------- | --------------------------- | ------------ |
| formatSource          | format      | format          | format     | prettier --write (js, scss) | format       |
|                       |             |                 |            | eslint --fix (js)           | lint:fix     |
|                       |             |                 |            | csslint --fix (css)         |              |
|                       |             |                 |            | csf -i (jsp, soy)           |              |
| checkSourceFormatting | checkFormat | lint            | lint       | prettier --check (js, scss) | format:check |
|                       |             |                 |            | eslint (js)                 | lint         |
|                       |             |                 |            | csslint (css)               |              |
|                       |             |                 |            | csf (jsp, soy)              |              |

We can't change Gradle names to make them consistent, but we are free to change pretty much anything else in the table, so I am proposing this:

| Gradle name           | Portal name | Subcommand name | Config key | Command(s)                  | GitHub name  |
| --------------------- | ----------- | --------------- | ---------- | --------------------------- | ------------ |
| formatSource          | fix         | fix             | fix        | (all of the below)          | fix          |
|                       |             |                 |            | prettier --write (js, scss) | format       |
|                       |             | lint:fix        | fix        | eslint --fix (js)           | lint:fix     |
|                       |             |                 |            | csslint --fix (css)         | n/a          |
|                       |             |                 |            | csf -i (jsp, soy)           | n/a          |
| checkSourceFormatting | check       | check           | check      | (all of the below)          | check        |
|                       |             |                 |            | prettier --check (js, scss) | format:check |
|                       |             | lint            | check      | eslint (js)                 | lint         |
|                       |             |                 |            | csslint (css)               | n/a          |
|                       |             |                 |            | csf (jsp, soy)              | n/a          |

Specifically:

- liferay-npm-scripts users will really only use "fix" and "check", which correspond to the default liferay-portal actions of "fix everything" and "check everything"; note that "fix" and "check" are used consistently across all the columns, including changing the names of the glob properties.
- We'll additionally add some new subcommands to liferay-npm-scripts that correspond to the GitHub names for the same actions ("lint" and "lint:fix"); these will really only used by use during the transition (#109) — we won't document them or promote their use; we can remove them later, which means that the final end state will actually be:

| Gradle name           | Portal name | Subcommand name | Config key | Command(s)                  | GitHub name  |
| --------------------- | ----------- | --------------- | ---------- | --------------------------- | ------------ |
| formatSource          | fix         | fix             | fix        | (all of the below)          | fix          |
|                       |             |                 |            | prettier --write (js, scss) | format       |
|                       |             |                 |            | eslint --fix (js)           | lint:fix     |
|                       |             |                 |            | csslint --fix (css)         | n/a          |
|                       |             |                 |            | csf -i (jsp, soy)           | n/a          |
| checkSourceFormatting | check       | check           | check      | (all of the below)          | check        |
|                       |             |                 |            | prettier --check (js, scss) | format:check |
|                       |             |                 |            | eslint (js)                 | lint         |
|                       |             |                 |            | csslint (css)               | n/a          |
|                       |             |                 |            | csf (jsp, soy)              | n/a          |

So the actions needed for now:

1. Rename "format" subcommand and glob to "fix" (in this repo) (this issue).
2. Add  (temporary) "lint" and "lint:fix" subcommands (in this repo); may even want a "lint:quiet" if it ends up being helpful (#109).
3. Deploy to liferay-portal and update configs, package.json files etc.
4. Document conventions for GitHub projects in [liferay-frontend-guidelines](https://github.com/liferay/liferay-frontend-guidelines).
5. Add "check" and "fix" tasks to GitHub projects that don't have then (some of them have a "ci" task that is basically equivalent to "check") — (in other GitHub repos).
6. (Later) Remove temporarily added "lint" and "lint:fix" commands (from this repo).

**Comment by bryceosterhaus** [comment]
> "The Portal Way™"

😂
