### ISSUE TITLE
jenkins is reporting js-unit tests twice

### ISSUE THREAD

**Issue by john-co** [liferay/liferay-npm-tools#137]
see example: https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/322879/AXIS_VARIABLE=0,label_exp=!master/testReport/frontend-taglib.frontend-taglib-clay.test/management_toolbar/

**Comment by wincent** [comment]
Looking in [the console output](https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/322879/AXIS_VARIABLE=0,label_exp=!master/consoleText) for that run, I see the ManagementToolbar tests running exactly once:

```
     [exec] > Task :apps:frontend-taglib:frontend-taglib-clay:npmRunTest
     [exec] PASS test/management_toolbar/ManagementToolbar.es.js (16.686s)
     [exec]   ManagementToolbar
     [exec]     ??? should listen to the rowToggled event from the registered search container (140ms)
     [exec]     ??? should deselect all searchContainer rows (36ms)
     [exec]     ??? should select all searchContainer rows (30ms)
     [exec]     ??? should toggle the searchContainer selected rows (27ms)
```

Could it be that something outside of `jest-junit-reporter` is cause the results to appear twice? Something in the `merge-test-results` task?

**Comment by wincent** [comment]
Closing this one due to inactivity and I need to clean out this repo before archiving it.

If there is still a demand for it, we can re-open this issue over at: https://github.com/liferay/liferay-frontend-projects/issues (which is where this repo has been migrated).
