### ISSUE TITLE
Missing `@babel/preset-react` from bundled presets

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-npm-tools#139]
We currently don't bundle any @babel preset for compiling react. Right now, segments-web is using [`@babel/preset-react: ^7.0.0`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/segments/segments-web/package.json#L22) and other projects are starting to use it. Since we don't allow having `devDependencies`,  they need it somewhere.

I assume we should bundle it with `npm-scripts`, but I may be wrong, so this should just serve as a conversation starter, not an order :D 

For now, I'll consolidate the plugin in the general `modules/package.json` of `liferay-portal`

**Comment by wincent** [comment]
> I assume we should bundle it with `npm-scripts`

That sounds right to me, just like we bundle the necessary webpack-related stuff with `liferay-npm-scripts`, we should bundle everything needed by Babel to address the common use cases in liferay-portal.
