### ISSUE TITLE
refactor of Jest config set-up caused issues with running jest

### ISSUE THREAD

**Issue by oliv-yu** [liferay/liferay-npm-tools#176]
Ever since version liferay-npm-scripts 4.7.0 I've been running into an issue with running 'yarn test', not quite sure why that is or if I needed to run my test differently. 

https://gist.github.com/oliv-yu/db0d48f873bca01b86f951d1c2379c57

Any ideas? Not sure

**Comment by wincent** [comment]
Looks like another one of those Windows-vs-Posix path things, although the error message isn't super helpful in signalling exactly what the root cause is. Let me see if I can repro this on the Windows laptop here and get back to you.

**Comment by wincent** [comment]
I was wondering if you might be running in to the [command-line argument length limit](https://stackoverflow.com/questions/3205027/maximum-length-of-command-line-string), which might be as low as 8k characters, but the Jest command it "only" about 2.5k characters long, so I don't think that's it... will keep digging.

**Comment by wincent** [comment]
This is fixed in v4.12.1 of liferay-npm-scripts. I'll send a PR to get that into liferay-portal shortly.

**Comment by oliv-yu** [comment]
Thank you!
