### ISSUE TITLE
Create a generic watch script

### ISSUE THREAD

**Issue by diegonvs** [liferay/liferay-npm-tools#2]
Would be cool if `liferay-npm-scripts` have a watch script like this example:

https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-builder/watch.js

**Comment by brunofarache** [comment]
@diegonvs @jbalsas just wanted to emphasize this is very important for development experience. My builds can take up to 1 minute and any change I do is painful.

I didn’t want to try any hack, I’m waiting for something more official, but if you guys think this will take longer, I will copy the hack from segments or workflow.

**Comment by jbalsas** [comment]
Hey @wincent, @izaera, I'm adding this to https://github.com/liferay/liferay-npm-tools/milestone/6 so we can track it down, wether it's by creating something else or simply piggy-backing the current `deployFast` mechanism with dir.overrides.

**Comment by izaera** [comment]
PR #316 makes the necessary changes to stop `deployFast` failing so I'm closing this as we will be able to use `deployFast` once we release a new version of this project and use it from portal.
