### ISSUE TITLE
CSS format: Alert using /* comment */

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/liferay-npm-tools#232]
Alert on uses of comments, /* comment */ will persist after a compilation

> **Rationale**: In SCSS multiline comments persist after a compilation, so we should choose single-line comments

Examples of **correct** code:

```
// first coment line
// second coment line
```

Examples of **incorrect** code:

```
/* first coment line
    second coment line */
```

**Comment by wincent** [comment]
Ooh. I forgot about this; I made the mistake of using a `/* ... */` comment the other day.

**Comment by wincent** [comment]
I added some more commits on top of https://github.com/liferay/liferay-npm-tools/pull/347 that will implement this via a custom "no-block-comments" rule, so this will get closed when that one gets merged.
