### ISSUE TITLE
Allow configurable output directory (or change default)

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-npm-tools#272]
As part of our build process, we take inputs and produce outputs. Right now, those outputs are going to the `classes/META-INF/resources `. As far as I can tell, we're defining this in:
- [packages/liferay-npm-scripts/src/presets/standard/index.js](https://github.com/liferay/liferay-npm-tools/blob/9a1017e740a12d435c7e88aa3c8fbf2ae415e0fa/packages/liferay-npm-scripts/src/presets/standard/index.js#L17) 
- [packages/liferay-npm-bundler-preset-liferay-dev/config.json](https://github.com/liferay/liferay-npm-tools/blob/6db5f4679f5ca6463fb8cb34c6c62af7ba15fd71/packages/liferay-npm-bundler-preset-liferay-dev/config.json#L264)

This should be in general ok, but is causing problems because of how it integrates with Gradle's input/output checks subsystem.

As per @petershin instructions, it would be ideal if we could:

> assuming liferay-npm-scripts build copies files to classes\META-INF\resources please update the script to output files to this directory: foo-web\build\node\packageRunBuild\resources

We could:
- Change the defaults `classes/META-INF/resources` to `build/node/packageRunBuild/resources`
- Additionally, make it configurable so the callers could change it

**Comment by wincent** [comment]
So just a question about this: at the moment, the "frontend" *input* files (ie. JS, SCSS, Soy) are under `src/main/resources/META-INF/resources`, mixed together with other files (ie. Java, JSP etc).

With this change, the frontend *output* files will be in a different directory. Will this be enough to give Peter what he wants? (seeing as our output files will be well delineated, but the input files will not — unless he's got enough control via globs to distinguish between frontend/non-frontend files.)

**Comment by jbalsas** [comment]
I think so, he will need to adjust the input globs accordingly.

**Comment by wincent** [comment]
Created https://issues.liferay.com/browse/LPS-102342 to track the integration of this into liferay-portal. As the rest of the work is going to continue over there, I'll close this one.
