### ISSUE TITLE
Add step to replace translations in soy files

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-npm-tools#277]
When compiling `.soy`, our tool implements an [--externalMsgFormat](https://github.com/metal/metal-tools-soy#externalmsgformat) param that converts calls to `goog.getMsg('foo')` to their equivalent `Liferay.Language.get('foo')`.

When integrated in `liferay-npm-scripts`, src soy files are properly processed, but those brought in as dependencies (and copied over via bundler) won't.

We could add something like https://github.com/metal/metal-tools-soy/blob/4.x/lib/pipelines/compileSoy.js#L61-L77 after the bundler step

```javascript
// gulp code
replace(EXTERNAL_MSG_REGEX, (match, p1, p2, p3) => {
	let externalMsg = match.replace(
		EXTERNAL_MSG_REGEX,
		`var $1 = ${options.externalMsgFormat};`
	);
	if (p3) {
		externalMsg = externalMsg.replace(/\{\$([^}]+)}/g, function(
			match,
			key
		) {
			return 'x';
		});

		externalMsg = externalMsg += `\n\t${p1} = ${p1}.replace(/{(\\d+)}/g, '\\x01$1\\x01');\n`;
	}
	return externalMsg;
})
```

**Comment by wincent** [comment]
I'll update these two pulls to @petershin to include this:

- https://github.com/petershin/liferay-portal/pull/719
- https://github.com/petershin/liferay-portal-ee/pull/172
