### ISSUE TITLE
Enable babel-plugin-transform-react-remove-prop-types in production builds

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-npm-tools#301]
Just learned that there is a [babel-plugin-transform-react-remove-prop-types](https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types) that we can use to streamline our production builds. 

As far as I can tell, we currently don't have a fork in our babel setup, but it should be pretty straightforward to start applying some optimizations for the `process.env.PRODUCTION` case.

**Comment by wincent** [comment]
🥚

**Comment by wincent** [comment]
There's also [transform-remove-prop-types](https://www.typescriptlang.org/). 😂

**Comment by diegonvs** [comment]
>There's also transform-remove-prop-types. 😂

+1 for Greg's answer 😂

**Comment by jbalsas** [comment]
> There's also transform-remove-prop-types. 😂

![oowow](https://user-images.githubusercontent.com/905006/68308439-29de5400-00ad-11ea-8265-ce6a3c2049e8.gif)

**Comment by wincent** [comment]
This rule might help us to activate this rule a little more safely: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-foreign-prop-types.md

**Comment by wincent** [comment]
Upstream PR: https://github.com/brianchandotcom/liferay-portal/pull/83326
