### ISSUE TITLE
Set @babel/preset-react as our default babel preset

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-npm-tools#303]
We currently have `env` as our default babel preset which forces as to override in any "react" module with:

#### .babelrc

```json
{
	"presets": [
		"@babel/preset-react"
	]
}
```

I currently count  **31 custom .babelrc** in `master` with the react preset, which likely means it's time for us to make this the default.

**Comment by wincent** [comment]
Upstream: https://github.com/brianchandotcom/liferay-portal/pull/83438
