### ISSUE TITLE
Set liferay/react as our default eslint base

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-npm-tools#304]
We currently have `liferay` as our default eslint base which forces as to override in any "react" module with:

#### .eslintrc.js

```javascript
module.exports = {
	extends: ['liferay/react']
};
```

I currently count  **32 custom .eslintrc.js** in `master` with the react extend, which likely means it's time for us to make this the default.

**Comment by wincent** [comment]
See the related ticket that I made in eslint-config-liferay for this: https://github.com/liferay/eslint-config-liferay/issues/107 — basically, it may not be that we make `liferay/react` the base, but rather, that we make the current default (`liferay/portal`) assume the presence of React instead.

**Comment by wincent** [comment]
Here's the change in eslint-config-liferay for this: https://github.com/liferay/eslint-config-liferay/pull/123

I'm going to test this in liferay-portal now and see what issues arise.

**Comment by wincent** [comment]
Upstream PR: https://github.com/brianchandotcom/liferay-portal/pull/81817
