### ISSUE TITLE
Update to Prettier v2.0.0

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-npm-tools#418]
Low-ish priority on this one because there may be some bugs that need to get sorted out in the next few patch releases, and this could generate a fair bit of churn:

https://prettier.io/blog/2020/03/21/2.0.0.html

But still, something we'll want to do at some point in order to benefit from the bug fixes.

**Comment by wincent** [comment]
Ok, I think most of the bugs in 2.0.x have been sorted out at this point (currently at 2.0.4). However, I think that trying to get a big change into liferay-portal at the moment is a fool's errand due to the state of CI, with trivial changes getting held up for many days due to flaky tests. So if we do this, which will touch hundreds of files, I don't expect it will be easy to merge it in. Having said that, maybe we *should* try to do it, because that may apply useful pressure on our CI/QA apparatus, and force us to sort our issues out.

**Comment by jbalsas** [comment]
I would go with the update, shortcut CI and send straight to Brian.

**Comment by wincent** [comment]
Quick self-PR is up at: https://github.com/wincent/liferay-portal/pull/211

In the weekly call with Brian on Wednesday, he wanted me to send a big change so that we stress test CI and discuss the results on the next call. So that's the test. If it doesn't work, I can do what you said @jbalsas and do the "real" update and just send it directly to Brian after Wednesday.

I have a few sweeping changes like (new lint rules etc) this which means I can send something "big" every week until the CI problems get a bit more under control.
