### ISSUE TITLE
feat: update Yarn, Babel, Jest dependencies

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-npm-tools#42]
- [x] Remove basically unused Lerna set-up.
- [x] Switch to Yarn workspaces.
- [x] Update Jest and Babel dependencies.

**Comment by bryceosterhaus** [comment]
@wincent So does yarn workspaces essentially remove the need of lerna? I had always thought it was weird to have both coexist but I never took the time to look into it.

**Comment by wincent** [comment]
Not exactly because there is some overlap between the tools.

Yarn workspaces take care of the linking between packages, and arguably does it in a much more reliable way than Lerna because it is baked right in to `yarn install`.

The thing that Lerna still does and which Yarn does not is provide a way to release all the packages at once. Having said that, in this repo, with only three packages, and in all likelihood, only one of them that we are going to release with any regularity ("liferay-npm-scripts"), that is not much of a value-add. The cost is a relatively large dependency footprint, which may or may not be worth it depending on your point of view. And I find it pretty disappointing that Lerna has been so slow to make publishing with 2FA livable; in the end I think you can get almost all the value that Lerna provides with a couple of small scripts.
