### ISSUE TITLE
Remove dodgy core-js import from bundler preset

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-npm-tools#446]
As reported [in Slack](https://liferay.slack.com/archives/C03CAD9EF/p1588703600080100).

We have had [set up since about 13 months ago](https://github.com/liferay/liferay-npm-tools/commit/fd4ee8d5aa5fcd74baae7bfb15f71bfa3a5dee4b) a config to obtain core-js from frontend-js-metal-web.

This seems a bit random as frontend-js-metal-web doesn't even have core-js as an explicit dependendency and never has (it became even more implicit in https://github.com/liferay/liferay-portal/commit/348faaa59aea359a2079f4048c11c7f364625d6a when we removed the package-lock.json file from that module).

The problem is somebody is trying to add a new library in liferay-portal which depends (transitively, I guess) on core-js and is trying to it from frontend-js-metal-web and failing.

Summary of [output of `yarn why core-js` in liferay-portal](https://gist.github.com/wincent/e8ab7749305507a3a9b7ff571591768c):

```
=> Found "core-js@3.1.4"
=> Found "analytics-client-js#core-js@2.6.11"
=> Found "recharts#core-js@2.6.11"
=> Found "fbjs#core-js@1.2.7"
=> Found "babel-runtime#core-js@2.6.11"
=> Found "babel-register#core-js@2.6.11"
```

Our preset says to get `>= 2.6.5` from frontend-js-metal-web. At you can see in the full `yarn why` output, frontend-js-metal-web doesn't even depend transitively on any version of core-js at the moment, so the preset is just wrong. In the Git history, it is hard to tell exactly when this transitive dependency went away; at least, nothing obvious stands out in the history of the `package.json`.

Immediate "fix" is to just remove the broken preset, which would mean that each module that needs core-js would end up using its own transitive copy. @jbalsas warns that this may slow the build because each module will have to build its own copy, but I am not sure this is actually true: if any modules were trying to re-use the non-existent shared copy of core-js I would think that they would already be exploding.

A better fix might be to create modules for each of the major core-js versions — 1.x, 2.x, 3.x — and configure the preset to point at those.

For reference, current references to core-js in liferay-portal:

- frontend-ie-compatibility pulls down a copy via webjars, so isn't participating in any kind ofnode_modules sharing.
- analytics-client-js is a basically independent project, and uses an independent copy inits webpack build.
- frontend-js-react-web, frontend-js-spa-web, and frontend-taglib-clay all have an `exclude` for core-js in their .npmbundlerrc; these all use liferay-npm-bundler-preset-standard, which means they don't "see" the liferay-npm-bundler-preset-liferay-dev referenced above anyway.

**Comment by jbalsas** [comment]
>  @jbalsas warns that this may slow the build because each module will have to build its own copy, but I am not sure this is actually true: if any modules were trying to re-use the non-existent shared copy of core-js I would think that they would already be exploding

Might be wrong here... basically what I did was, look at `classes/META-INF/node_modules` at the time for basically every module we were compiling to see what was in there. Many of them, for whatever reason, had `core-js` in there at the moment.

> [...] so the preset is just wrong [...]

That is very possible indeed :)

**Comment by izaera** [comment]
The preset is wrong in the sense that `exclude`s `core-js` for each project and then tells them to import it from `frontend-js-metal-web`, where it isn't.

However, up to the day, nothing has broken, which means that even if the projects have `core-js` as a dependency, they are not using it :shrug:.

So..., if we stop excluding `core-js` we will impact the build times to get nothing, I guess. But on the other hand, the preset shouldn't be plain wrong, I suppose.

I suppose the best solution is what @wincent says is a better fix: 

> create modules for each of the major core-js versions — 1.x, 2.x, 3.x — and configure the preset to point at those.

We can create a `frontend-js-core-js` module or provide it from `frontend-js-web` or something similar...

**Comment by izaera** [comment]
The description of `core-js` says it all:

![imagen](https://user-images.githubusercontent.com/3273630/81265681-cb863400-9043-11ea-8b50-3ca310315151.png)

Who wouldn't want to have the `standard library` in their projects? :shrug:

**Comment by wincent** [comment]
Seeing as I'm going to cut a liferay-npm-scripts release today, I'm going to "fix" the preset and leave the whole "frontend-js-core-js" thing for another day. In reality, I would hope that our runtime deps in liferay-portal wouldn't make much (or any) use of core-js at all (and evidently, they haven't in the past, so who knows how long before this actually comes up again).
