### ISSUE TITLE
yarn format empties `.babelrc.js` files

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-npm-tools#456]
See https://github.com/wincent/liferay-portal/pull/301#issuecomment-634621120

**Comment by wincent** [comment]
It does that because it thinks the presets aren't needed (it is a lint autofix), but you can get around that by [turning off the lint like I said here](https://github.com/wincent/liferay-portal/pull/301#issuecomment-634654827).

**Comment by izaera** [comment]
closing this as it is the intended behavior
