### ISSUE TITLE
liferay-npm-scripts doesnt translate react-datetime correctly

### ISSUE THREAD

**Issue by rahulahoop** [liferay/liferay-npm-tools#461]
react-datepicker has a dependency to object-is.

Object-is's index file is like this (before translation)

```
'use strict';

var define = require('define-properties');
var callBind = require('es-abstract/helpers/callBind');

var implementation = require('./implementation');
var getPolyfill = require('./polyfill');
var shim = require('./shim');

var polyfill = callBind(getPolyfill(), Object);

define(polyfill, {
	getPolyfill: getPolyfill,
	implementation: implementation,
	shim: shim
});

module.exports = polyfill;
```

This causes issue in browser "defined is not defined" because liferay-npm-scripts fails to convert this class and add the Liferay.Loader.define() to the translated file; assumedly because there is already a define fnc/method here. 
In browser, it is translated like this;
![Screen Shot 2020-06-03 at 3 59 38 PM](https://user-images.githubusercontent.com/7705259/83645853-3da25800-a5b3-11ea-8635-40ff2b7989df.png)

As you can see there is no Liferay.Loader.define, but only a define.

This prevents react-datepicker from being used in liferay, and in turn any lib using a method with define()

**Comment by wincent** [comment]
Could you please [re-file this one](https://github.com/liferay/liferay-js-toolkit/issues/new) over in the [liferay-js-toolkit repo](https://github.com/liferay/liferay-js-toolkit)? That's where the for the liferay-npm-bundler lives, which is responsible for rewriting to `Liferay.Loader.define` etc.

**Comment by rahulahoop** [comment]
@wincent but i am using liferay-npm-scripts in my projet..

**Comment by wincent** [comment]
`liferay-npm-scripts` [just calls `liferay-npm-bundler`](https://github.com/liferay/liferay-npm-tools/blob/99616001be0c1a221b84affa7ab6294bee3420f2/packages/liferay-npm-scripts/src/utils/runBundler.js#L20-L24). It has no business looking inside or modifiying the artifacts that the bundler makes. You should open the issue over on [liferay-js-toolkit](https://github.com/liferay/liferay-js-toolkit) instead.

**Comment by rahulahoop** [comment]
already done 🙃
