### ISSUE TITLE
Evaluate continued use of "Gitflow" branching model in this repo

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-npm-tools#47]
Splitting this off from https://github.com/liferay/liferay-npm-tools/issues/40 where @jbalsas [said](https://github.com/liferay/liferay-npm-tools/issues/40#issuecomment-476686439):

> I'm also not sure we have a common merge strategy here either...

and @bryceosterhaus said:

> As for merge strategy, is there any other guidelines we follow for other projects? It'd be nice to outline general contributing rules for portal and non-portal related gh projects

The purpose of this issue then, is to discuss that question and see if we want to make a change. I'll copy-paste my comment from the other issue below.

**Comment by wincent** [comment]
Copy-pasting [my previous comment](https://github.com/liferay/liferay-npm-tools/issues/40#issuecomment-477095985) below:

-----

I know that in most but not all Liferay projects outside of portal we follow — more or less — the "Gitflow" workflow described here:

- https://nvie.com/posts/a-successful-git-branching-model/
- https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

Examples:

- [Clay](https://github.com/liferay/clay) uses it, as does [liferay-npm-build-tools](https://github.com/liferay/liferay-npm-build-tools) and I suspect many others.
- Some projects are very simple and work just from "master", like [eslint-config-liferay](https://github.com/liferay/eslint-config-liferay).
- [liferay-amd-loader](https://github.com/liferay/liferay-amd-loader) is an example of a project which doesn't use "Gitflow" (just works off master), but also has release branches (eg. [2.x](https://github.com/liferay/liferay-amd-loader/tree/2.x) and [3.x](https://github.com/liferay/liferay-amd-loader/tree/3.x), which TBH look seldom updated).

I am pretty skeptical of "Gitflow" myself. I think for simple projects it brings unnecessary complexity, and for more complicated projects, er, it probably bring unnecessary complexity there too. It's all too easy to send a pull request to the wrong branch, and then we have confusion like we've seen in Clay where people [apparently don't know where the work is happening](https://github.com/liferay/clay/pull/1674).

In both [alloy-editor](https://github.com/liferay/alloy-editor) and [liferay-js-themes-toolkit](https://github.com/liferay/liferay-js-themes-toolkit) we actually moved away from "Gitflow" and back to a more conventional develop-on-master approach. We still have a branch that we update after every release, but it's just not called "master" any more:

- In AlloyEditor:
  - new development work for v2.0 happens in "master".
  - after each release "stable" gets fast-forwarded to match "master".
  - work on the legacy v1.x versions happens on "1.x" (we still need to cut releases there occasionally).
  - after each v1.x release "1.x-stable" gets fast-forwarded to match "1.x".
- In the themes toolkit:
  - new development work for v9.0 happens in "master".
  - after each release "stable" gets fast-forwarded to match "master".
  - work on the legacy v8.x versions happens on "8.x" (we still need to cut releases there occasionally).
  - after each v8.x release "8.x-stable" gets fast-forwarded to match "8.x".

Basically, we're optimizing for making the common case as easy as possible: that is, the bulk of our work happens on "master". I think that these projects where we need to maintain multiple long-lived release branches are more likely the exception than the rule, and most of our projects could just use a simple "do it on master" model. Even the value of the "stable" branch is debatable, although it doesn't cost that much to keep it around.

-----

My proposal, at least for this project, would be to scrap "develop" and do everything on "master". We can create a "stable" branch to fulfil the role that "master" is currently fulfilling. I'm mostly motivated by wanting to simplify; even though I try to pay attention to which branch I'm on I still manage to mess up from time to time (the most recent example being today in this very repo when I accidentally merged something to "master" when it should have gone to "develop", and I had to fix that by creating [a merge commit](https://github.com/liferay/liferay-npm-tools/commit/954165573c9c086bfd64672a71d6d3d411f937b9) that otherwise would have been unnecessary.).

**Comment by jbalsas** [comment]
As we've discussed this for other projects, this sounds good to me, I'm not particularly committed to a specific flow, whatever's easier for us to develop and maintain 👍

**Comment by bryceosterhaus** [comment]
> My proposal, at least for this project, would be to scrap "develop" and do everything on "master". We can create a "stable" branch to fulfil the role that "master" is currently fulfilling.
👍👍👍

Totally agree with this idea. Gitflow, no matter how many times I interact with repos that use it, it always confuses me or catches me off guard. It requires too much upfront knowledge and inner workings and its hard to safeguard from mistakes.

**Comment by wincent** [comment]
Sweet. I'm going to do the following:

- [ ] Fast-forward "master" to current HEAD of "develop".
- [ ] Create "stable" at same commit, just as a starting point; having "stable" may even be overkill for this repo, but the worst case scenario is that we don't find it very useful and we forget to update it. 😭
- [ ] Update "develop" by deleting everything and creating a README explaining that the branch has been retired; in this way, nobody will be able to accidentally push to it because they'll get a conflict.
- [ ] Update CONTRIBUTING.md (#49) to reflect the new structure.
