### ISSUE TITLE
Include @testing-library/react-hooks library

### ISSUE THREAD

**Issue by victorg1991** [liferay/liferay-npm-tools#496]
Could we include the `@testing-library/react-hooks` library to be used within the tests? https://github.com/testing-library/react-hooks-testing-library

We had some misunderstandings and the library is already included in the portal workspace because it is added in [portal-workflow-metrics-web package.json](https://github.com/liferay/liferay-portal/blob/f86d976d9f59933928199ee8b57ebee1c88efbd7/modules/dxp/apps/portal-workflow/portal-workflow-metrics-web/package.json#L36) (using a SF supression) and used [here](https://github.com/liferay/liferay-portal/blob/fe37327dbe1e88de73f83075d7d18ee91c00dc26/modules/apps/layout/layout-content-page-editor-web/test/page_editor/app/components/undo/useUndo.test.js)

To avoid disabling the current test I think it would be better for [this pr](https://github.com/liferay-frontend/liferay-portal/pull/384) to wait until we include the library 'officially' so that we can remove the supression while the tests continue working

**Comment by wincent** [comment]
I'm testing a release of the script with this new dependency today.

**Comment by wincent** [comment]
I cut a release and folded it into [this PR](https://github.com/liferay-frontend/liferay-portal/pull/384), so follow along there if you want to track when this gets into liferay-portal.
