### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-npm-tools#69]
We have Travis CI enabled for this repo, so we can now enable CI on our PRs and pushes as we see fit 😉 

<img width="674" alt="Screen Shot 2019-04-09 at 11 12 55" src="https://user-images.githubusercontent.com/905006/55788415-8b5b2780-5ab8-11e9-91ec-bae3e7cbc1f8.png">

/cc @wincent

**Comment by wincent** [comment]
Awesome!

```javascript
expect(tests).toPass();
```
