### ISSUE TITLE
Recover original .npmbundlerrc file when bundler fails

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-npm-tools#71]
Right now, if the build fails, sometimes the modified `.npmbundlerrc` is left and the original one is lost. It would be great if the script could recover from such situation and restore the original `.npmbundlerrc`.

Alternatively, we could modify the `liferay-npm-bundler` (in addition to the scripts) so that it could receive the path to the `.npmbundlerrc` and that way we would execute it with a temporary one and leave the project's one untouched.

**Comment by wincent** [comment]
> Alternatively, we could modify the `liferay-npm-bundler` (in addition to the scripts) so that it could receive the path to the `.npmbundlerrc` and that way we would execute it with a temporary one and leave the project's one untouched.

I think that would be great. I was pretty horrified — only exaggerating a *little* bit — when I saw how config merging worked in this repo by overwriting and then restoring the config files.

The "nice" thing about mutating the config is that it is left on the filesystem for you to inspect when things go wrong, but I think we can have that same benefit with a temporary config file too if we just emit the path to it in the console output.
