### ISSUE TITLE
passing env params for testing

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/liferay-npm-tools#88]
I do not know if by default the tests should have the env of `test` or we should just inherit the envs. This is required for Metal testing inside the portal.

**Comment by wincent** [comment]
@matuzalemsteles Are you referring to `NODE_ENV` or something else?

**Comment by matuzalemsteles** [comment]
Oh sorry for not being clear with this, just the `NODE_ENV`.

**Comment by wincent** [comment]
Setting `NODE_ENV` to `test` seems pretty reasonable to me, and Jest [should do it by default](https://raw.githubusercontent.com/facebook/jest/4ba05b7d4c5a9f8acd75fec529da2e2543422a81/docs/GettingStarted.md):

> Jest will set `process.env.NODE_ENV` to `'test'` if it's not set to something else.

Seems we're setting it to "production" [here](https://github.com/liferay/liferay-npm-tools/blob/ab2cc17d473637f7bd034c7940c0d7b2bde1a428/packages/liferay-npm-scripts/src/scripts/test.js#L9). @bryceosterhaus: do you remember your rationale for doing that?

**Comment by matuzalemsteles** [comment]
@wincent I think setting the `process.env` in this way will not influence the Jest call, I think we would have to configure the env of [spawnSync](https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options) I'm not sure about this, the documentation is not very clear.

**Comment by wincent** [comment]
@matuzalemsteles I think the environment is inherited automatically; try this in the `node` REPL:

```
process.env.ZZZZZ = 'hi'
console.log(require('child_process').spawnSync('/usr/bin/env').stdout.toString())
```

You'll see:

```
[ a bunch of env variables]
ZZZZZ=hi
```

**Comment by bryceosterhaus** [comment]
@wincent I had gotten the idea from react-scripts, [here](https://github.com/facebook/create-react-app/blob/e7a2d6168a3a93ea58bafdc851eb2bbda20d5ce6/packages/react-scripts/scripts/build.js#L12). I think we can follow the same pattern and isolate it to the `build` script only though. The main idea for this would be to ensure the proper NODE_ENV for babel.

**Comment by matuzalemsteles** [comment]
Thanks @wincent seems to work fine. @bryceosterhaus for the test case, do we need it in `production`? it may not be necessary for testing.

**Comment by bryceosterhaus** [comment]
@matuzalemsteles it shouldn't be necessary for testing, but I think for `build` we should still have it.

**Comment by matuzalemsteles** [comment]
Yeah I agree on the `build`.
