### ISSUE TITLE
Provide better error messages for duplicate plug-ins

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-npm-tools#89]
We recently added `@babel/plugin-proposal-class-properties` and `@babel/plugin-proposal-object-rest-spread` to our default config. If somebody creates a `.babelrc` with the same plugins but different names (possible because Babel allows for various shorthand notations), then we will end up passing both through and Babel will complain about the duplicates.

Example case of this and [the fix here](https://github.com/arboliveira/liferay-portal/pull/742/commits/a6ac0133391f8508eea117d1241912c58da75628) (ie. removing the duplicate). Sadly, Babel's error message isn't helpful:

```
Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]
```

because it doesn't say which plug-ins are duplicated. And even if it did, it wouldn't be easy for people to troubleshoot because we dynamically create a `.babelrc` at runtime, so they'll probably inspect what they have on disk and wonder why there are being told there's a duplicate.

We have two options here to make a better experience:

- Normalize plug-in names to shorthand format before merging, thus silently eliminating duplicates.
- Normalize plug-in names to shorthand format, and if duplicates found, print an actually helpful error message instead.

I think the latter is better, because otherwise we may wind up with redundant config in our repo. It will be harmless, but still redundant. I'd rather people get a clear error that tells them how to remove the redundancy.

**Comment by bryceosterhaus** [comment]
> Normalize plug-in names to shorthand format, and if duplicates found, print an actually helpful error message instead.

+1
