### ISSUE TITLE
Swap out CSF for prettier

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/liferay-npm-tools#93]
We got approval to move portal's js to be formatted with prettier rather than csf. See https://github.com/brianchandotcom/liferay-portal/pull/73576

To go this route we need to make the change in `liferay-npm-scripts` and then submit a pull to portal with the updated version and running format. The prettier config will be located here in `liferay-npm-scripts` and the rules for that can be seen here, https://github.com/brianchandotcom/liferay-portal/pull/73576/files#diff-7f33ec48d01d2b893151bb61f68b930a.

The `.prettierrc` would be added to root of liferay-portal. This is for text editors to automatically pick up the prettier config.

We should also slowly transition some of the rules we had in CSF to our eslint config.

**Comment by matuzalemsteles** [comment]
hey @bryceosterhaus just a question, when you say make a slow transaction of the CSF rules to eslint config, does it mean that we still have the CSF reigning during this transition?

**Comment by bryceosterhaus** [comment]
@matuzalemsteles the plan would be to entirely remove CSF and replace with prettier. And then in addition we would likely need to add eslint and use the liferay preset. We would then slowly add more rules as needed.

**Comment by matuzalemsteles** [comment]
Great, thanks for information.
