### ISSUE TITLE
Restore .soy and .jsp formatting

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-npm-tools#98]
In #96 we replaced `csf` with `prettier` and in the process temporarily dropped support for formatting ".soy" and ".jsp" files.

That's ok as a temporary thing in the name of expediency because we have a limited window of opportunity to roll out a big change like switching to Prettier in liferay-portal. Having said that, we should go back and probably re-add "csf" just for the purposes of formatting those filetypes, because I doubt that Prettier is going to get support for those for the foreseeable future (and even if we did want to push for it and implement it ourselves, we'd need a stopgap measure).

Labelling this as a "feature", even though you could look at dropping support as a "bug" or regression. I'm just a positive guy. I can't help it.

**Comment by wincent** [comment]
Created corresponding internal ticket for this here: https://issues.liferay.com/browse/LPS-98032

See also [this comment](https://github.com/brianchandotcom/liferay-portal/pull/75474#issuecomment-509839687) from Brian, which is about sorting params in soy templates — I am not sure whether `csf` was ever able to do that, but if it was, then reactivating it for ".soy" files should take care of it, and if not we'll have to take a look into how best to do it.

**Comment by wincent** [comment]
Example PR that (presumably manually?) sorts params: https://github.com/brunobasto/liferay-portal/pull/1062

**Comment by wincent** [comment]
Note that in https://github.com/brianchandotcom/liferay-portal/pull/77453 we discuss an alternative (or perhaps additional) approach which is to extract JS from JSP files, pipe through Prettier, and then reinject it. The obvious challenge there is making sure that all the interpolated sections don't get broken by the formatting, or in turn make the formatting produce a suboptimal result.

**Comment by jbalsas** [comment]
So, the problem with good ol' `csf` is that it is a pretty manual process. The difference will still be very noticeable in jsps since they won't be applying prettier, so it will still be a very manual labour.

I think we'd better attempt leveraging Prettier somehow to make sure those stay consistent.

**Comment by jbalsas** [comment]
Hey @wincent, given that we restored `.jsp` formatting and that we're mostly got rid of `.soy` in `7.2.x` where we're applying it... do you think it would make sense to close this, or do you want to keep it open as a reminder?

**Comment by wincent** [comment]
Let's just close it and if we get another request to do formatting in `.soy` stuff we can create a new issue for that.
